TutorialSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zenith.urls', namespace='zenith')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zenith/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='zenith'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contactus/', views.contactus, name='contactus'),
    path('signup/', views.signup, name ='signup'),
    path('signin/', auth_views.LoginView.as_view(), name='login'),
    path('signout/', views.signout, name = 'logout'),
    path('studentregister/', views.studentregister, name='studentregister'),
    path('image_upload/', views.hotel_image_view, name = 'image_upload'),
    path('viewprofile/', views.viewprofile, name='studentprofile'),
    path('editprofile/<int:_id>/',views.editprofile, name='editprofile'),
    path('editdp/<int:_id>/',views.editdp, name='editdp'),
    path('message/',views.message, name='message'),
    path('payments/',views.payment, name='paymenthome'),
    path('paymentfile/',views.paymentfile, name='paymentfile'),
    path('paymentdetail/',views.paymentdetail, name='paymentdetail')
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

zenith/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    verified=models.BooleanField(default=False)
    hostel_address=models.CharField(max_length=100)
    date_of_birth=models.DateField()
    school=models.CharField(max_length=100)
    level = models.CharField(max_length=100)
    department=models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    lecture_theatre=models.CharField(max_length=100)
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Student: {self.owner}. Verified: {self.verified}"

class dp(models.Model):
    display_picture = models.ImageField(upload_to='images/', blank=True, null=True)
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Dp of {self.owner}"

class Payment(models.Model):
    full_name= models.CharField(max_length=100)
    email= models.EmailField()
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Payment details of {self.owner}"

class PaymentFile(models.Model):
    payment_file=models.FileField()
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Payment File of {self.owner}"

class Message(models.Model):
    full_name=models.CharField(max_length=100)
    email=models.EmailField()
    message=models.TextField()
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Message from {self.owner}"

zenith/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Student, Message, dp, Payment, PaymentFile


class RegisterForm(UserCreationForm):
    first_name=forms.CharField(max_length=30, required=True, help_text='Enter your First Name')
    last_name=forms.CharField(max_length=30, required=True, help_text='Enter Your Last Name')
    email=forms.EmailField(max_length=50, help_text='Enter a valid email address')

    class Meta:
        model=User
        fields=('username','first_name','last_name','email','password1','password2')

class StudentRegisterForm(forms.ModelForm):
    date_of_birth=forms.DateField(required=True, help_text='Enter Your Date of Birth in (yyyy-mm-dd)')
    school=forms.CharField(required=True, help_text='Enter the Full Name of your Institution of Learning')
    phone_number = forms.CharField(required=True, help_text='A WhatsApp Enabled Phone Number is Required')
    hostel_address = forms.CharField(required=True, help_text='Enter your Hostel Address in Full')
    level = forms.CharField(required=True, help_text='Enter Your Level')
    department=forms.CharField(required=True, help_text='Enter Your Department')
    lecture_theatre=forms.CharField(required=True, help_text='Enter the Name of the Lecture Theatre Where You Receive Most Lectures')

    class Meta:
        model = Student
        fields=['date_of_birth','school','phone_number','hostel_address','level','department','lecture_theatre']
        labels={}

class DpForm(forms.ModelForm):
    display_picture=forms.ImageField(required=True, help_text='Add a Clear Image of You')

    class Meta:
        model = dp
        fields = ['display_picture']

class MessageForm(forms.ModelForm):
    full_name=forms.CharField(required=True, help_text='Enter Your Full Name')
    email=forms.EmailField(required=True, help_text='Enter Your Email To Receive Response From Zenith Tutorial')
    message=forms.Textarea()

    class Meta:
        model=Message
        fields=['full_name','email','message']
        labels={}

class PaymentForm(forms.ModelForm):
    full_name=forms.CharField(required=True, help_text='Enter Your Full Name')
    email=forms.EmailField(required=True, help_text='Enter Your Email To Receive Payment Updates From Zenith Tutorial')

    class Meta:
        model=Payment
        fields=['full_name','email']
        labels={}

class PaymentFileForm(forms.ModelForm):
    payment_file=forms.FileField(required=True, help_text='Add File of Debit Alert in jpg/png/pdf/doc/docx')

    class Meta:
        model=PaymentFile
        fields=['payment_file']
        labels={}

zenith/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, logout, login
from .forms import RegisterForm, StudentRegisterForm,MessageForm, DpForm, PaymentForm, PaymentFileForm
from .models import Student, dp
# Create your views here.

def home(request):
    return render(request, 'zenith/home.html')

@login_required
def message(request):
    if request.method != 'POST':
        form = MessageForm()
    else:
        # Process completed form.
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.owner=request.user
            message.save()
            return HttpResponseRedirect(reverse('zenith:home'))
    context = {'form': form}
    return render(request, 'zenith/message.html', context)

@login_required
def paymentfile(request):
    if request.method != 'POST':
        form = PaymentFileForm()
    else:
        # Process completed form.
        form = PaymentFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.owner=request.user
            file.save()
            return HttpResponseRedirect(reverse('zenith:paymentdetail'))
    context = {'form': form}
    return render(request, 'zenith/paymentfile.html', context)

@login_required
def paymentdetail(request):
    if request.method != 'POST':
        form = PaymentForm()
    else:
        # Process completed form.
        form = PaymentForm(request.POST)
        if form.is_valid():
            detail = form.save(commit=False)
            detail.owner=request.user
            detail.save()
            return HttpResponseRedirect(reverse('zenith:paymenthome'))
    context = {'form': form}
    return render(request, 'zenith/paymentdetail.html', context)

@login_required
def payment(request):
    return render(request, 'zenith/payment.html')

@login_required
def viewprofile(request):
    data=Student.objects.filter(owner=request.user)
    hotel=dp.objects.filter(owner=request.user)
    context={'data':data, 'hotel':hotel}
    return render(request, 'zenith/studentprofile.html', context)

@login_required
def editprofile(request, _id):
    data=Student.objects.get(id=_id)
    if request.method != 'POST':
        form = StudentRegisterForm(instance=data)
    else:
        form = StudentRegisterForm(instance=data, data=request.POST)
        if form.is_valid():
            new_profile=form.save(commit=False)
            new_profile.owner=request.user
            new_profile.save()
            return HttpResponseRedirect(reverse('zenith:studentprofile'))
    context = {'data': data, 'form': form}
    return render(request, 'zenith/editprofile.html', context)

@login_required
def editdp(request, _id):
    data=dp.objects.get(id=_id)
    if request.method != 'POST':
        form = DpForm(instance=data)
    else:
        form = DpForm(request.POST, request.FILES)
        if form.is_valid():
            data.delete()
            new_dp=form.save(commit=False)
            new_dp.owner=request.user
            new_dp.save()
            return HttpResponseRedirect(reverse('zenith:studentprofile'))
    context = {'data': data, 'form': form}
    return render(request, 'zenith/editdp.html', context)

@login_required
def studentregister(request):
    if request.method != 'POST':
        form = StudentRegisterForm()
    else:
        # Process completed form.
        form = StudentRegisterForm(request.POST)
        if form.is_valid():
            new_student = form.save(commit=False)
            new_student.owner=request.user
            new_student.save()
            return HttpResponseRedirect(reverse('zenith:home'))
    context = {'form': form}
    return render(request, 'zenith/studentregister.html', context)

@login_required
def hotel_image_view(request):
  
    if request.method == 'POST':
        form = DpForm(request.POST, request.FILES)
  
        if form.is_valid():
            display=form.save(commit=False)
            display.owner=request.user
            display.save()
            return HttpResponseRedirect(reverse('zenith:studentregister'))
    else:
        form = DpForm()
    return render(request, 'zenith/imageform.html', {'form' : form})

@login_required
def aboutus(request):
    return render(request, 'zenith/aboutus.html')

@login_required
def contactus(request):
    return render(request, 'zenith/contactus.html')

def signup(request):
    if request.method != 'POST':
        form = RegisterForm()
    else:
        # Process completed form.
        form = RegisterForm(data=request.POST)
 
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('zenith:image_upload'))

    context = {'form': form}
    return render(request, 'zenith/signup.html', context)

@login_required
def signout(request):
    logout(request)
    return redirect('zenith:home')

zenith/templates/zenith/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title></title>

    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" rel="stylesheet">
    <script src="//code.jquery.com/jquery.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>\

    <style>
        html,
        body {
          height: 100%;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 60px; /* Set the fixed height of the footer here */
            background-color: #333;
        }
    </style>

<script>
function saylogout()
{alert('Goodbye User, We Hope To See You Soon');}
</script>

  </head>

  <body>
<a name="top"></a>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand active" href="#">Zenith Tutorial</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'zenith:home' %}">Home</a></li>
            <li class="active"a><a href="{% url 'zenith:aboutus' %}">About</a></li>
            <li class="active"><a href="{% url 'zenith:contactus' %}">Contact</a></li>
            <li class="active"><a href="{% url 'zenith:paymenthome' %}">Payments</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'zenith:studentprofile' %}">Hi {{ user.username|title }}</a></li>
                <li><a href="{% url 'zenith:studentprofile' %}">Student Profile</a></li>
                <li><a href="{% url 'zenith:logout' %}" onclick="saylogout()">Log Out</a></li>
                {% else %}
                <li><a href="{% url 'zenith:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'zenith:login' %}">Log In</a></li>
                {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

        <div class="page-header">

            {% block header %}{% endblock header %}

        </div>

        <div>

            {% block content %}{% endblock content %}

        </div>

    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted" style="text-align: center;"><a href="#top">Back To Top</a><br><br><a href="http://github.com/PeterOlayemi">Developer: PeterCodes</a></p>
      </div>
    </footer>

  </body>
</html>

zenith/templates/zenith/contactus.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Contact Us</title>
        <style>
            .blog-post-title {
                margin-bottom: 5px;
                font-size: 40px;
            }
        </style>
<script>
function linkedin()
{alert('Redirecting To LinkedIn');}
function facebook()
{alert('Redirecting To Facebook');}
function whatsapp()
{alert('Redirecting To WhatsApp');}
function mail()
{alert('Redirecting To Mail');}
</script>
    </head>
    <body>
    {% extends "zenith/base.html" %}

{% block header %}

    <div class=''>
        <div class="container">
        <br><br><br><br><br><h2 class="blog-post-title">Contact Us</h2>
        </div>
    </div>

{% endblock header %}

{% block content %}
<div style="font-size: 19px;">
    Dear Esteemed Student of Zenith,<br>If you have any questions, reviews or criticisms, you can always reach us by filling this <a href="{%url 'zenith:message'%}"><u>Simple Form Here &raquo;</u></a><br>
    A reply will be sent to the email address added to this form in 3 working days. <br>Kindly bear with us.<br><br><br>
    You can also visit our social media platforms below...
    <ul>
        <li>LinkedIn: <a href="https://linkedin.com/in/zenith" onclick="linkedin()">Zenith Tutorial</a></li>
        <li>Facebook: <a href="https://facebook.com/zenith" onclick="facebook()">Zenith Tutorial</a></li>
        <li>WhatsApp: <a href="https:wa.me/23450356890" onclick="whatsapp()">+23450356890</a></li>
        <li>Mail: <a href="mailto:zenithtutorial@gmail.com?subject=Enter Subject&body=Hi Zenith, ..." onclick="mail()">zenithtutorial@gmail.com</a></li>
    </ul>
<br><br><br><a href="{% url 'zenith:home' %}" class="btn btn-lg btn-default">&laquo; Go To Home</a>
</div>
<br><br><br><br><br><br><br><br>
{%endblock%}

zenith/templates/zenith/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Zenith Tutorial</title>
    <style>
a,
a:active,
a:focus,
a:hover {
  color: #fff;
}

/* Custom default button */
.btn-default,
.btn-default:hover,
.btn-default:focus {
  color: #333;
  text-shadow: none; /* Prevent inheritance from `body` */
  background-color: #fff;
  border: 1px solid #fff;
}


/*
 * Base structure
 */

html,
body {
  height: 100%;
  background-color: #333;
}
body {
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 3px rgba(0, 0, 0, .5);
}

/* Extra markup and styles for table-esque vertical and horizontal centering */
.site-wrapper {
  display: table;
  width: 100%;
  height: 100%; /* For at least Firefox */
  min-height: 100%;
  -webkit-box-shadow: inset 0 0 100px rgba(0, 0, 0, .5);
  box-shadow: inset 0 0 100px rgba(0, 0, 0, .5);
}
.site-wrapper-inner {
  display: table-cell;
  vertical-align: top;
}
.cover-container {
  margin-right: auto;
  margin-left: auto;
}

/* Padding for spacing */
.inner {
  padding: 30px;
}


/*
 * Header
 */
.masthead-brand {
  margin-top: 10px;
  margin-bottom: 10px;
  
}

.masthead-nav > li {
  display: inline-block;
  margin-left: -40px;
}
.masthead-nav > li + li {
  margin-left: 40px;
}
.masthead-nav > li > a {
  padding-right: 0;
  padding-left: 0;
  font-size: 16px;
  font-weight: 700;
  color: #fff; /* IE8 proofing */
  border-bottom: 2px solid transparent;
}
.masthead-nav > li > a:hover,
.masthead-nav > li > a:focus {
  background-color: transparent;
}
.masthead-nav > .active > a,
.masthead-nav > .active > a:hover,
.masthead-nav > .active > a:focus {
  color: #fff;
  border-bottom-color: #fff;
}

/*
 * Cover
 */

.cover {
  padding: 0 20px;
}
.cover .btn-lg {
  padding: 10px 20px;
  font-weight: 700;
}


/*
 * Footer
 */

.mastfoot {
  color: #999; /* IE8 proofing */
  color: rgba(255, 255, 255, .5);
}


/*
 * Affix and center
 */

@media (min-width: 768px) {
  /* Pull out the header and footer */
  .masthead {
    top: 0;
  }
  .mastfoot {
    position: fixed;
    bottom: 0;
  }
  .site-wrapper-inner {
    vertical-align: middle; /* Start the vertical centering */
  }
  .masthead,
  .mastfoot,
  .cover-container {
    width: 100%; /* Must be percentage or pixels for horizontal alignment */
  }
}

@media (min-width: 992px) {
  .masthead,
  .mastfoot,
  .cover-container {
    width: 700px;
  }
}
.footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 60px; /* Set the fixed height of the footer here */
            background-color: #333;
        }

    </style>
<script>
function saylogout()
{alert('Goodbye User, We Hope To See You Soon');}
</script>
  </head>

  <body>
<div style="font-size: 19px;">
    <div class="site-wrapper">

      <div class="">

        <div class="cover-container">

          <div class="">
            <div class="inner">
              <h2 class="">Zenith Tutorial</h2><br>
              <nav>
                <ul class="masthead-nav">
                  <li class="active"><a href="{% url 'zenith:home' %}">Home</a></li>
                  <li><a href="{% url 'zenith:aboutus' %}">About</a></li>
                  <li><a href="{% url 'zenith:contactus' %}">Contact</a></li><br><br>
                  <li><a href="{% url 'zenith:paymenthome' %}">Payments</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'zenith:studentprofile' %}">Student Profile</a></li><br><br>
                <li><a href="{% url 'zenith:logout' %}" onclick="saylogout()">Log Out</a></li>
                {% else %}
                <br><br><li><a href="{% url 'zenith:signup' %}">Sign Up</a>
                <li><a href="{% url 'zenith:login' %}">Log In</a></li>
                {% endif %}
                </ul>
              </nav>
            </div>
          </div>
{% if user.is_authenticated %}
<div style="text-align:left;">Hello {{ user.username|title }}...</div><br><br><br><br>
{% else %}
{% endif %}
          <div class="inner cover">
            <h1 class="cover-heading">Welcome To Our Official Student's Website</h1>
            <br><p class="lead">Zenith Tutorial is a LAUTECH- and KWASU-based tutorial provider that provides high-quality tutorial for 100 level students across these schools who are ready to bag a first-class in their results. With the production of 100 students with a CGPA of 5.0 in the last two sessions, Zenith tutorial has proven to the best tutorial provider in these two schools and Nigeria at large. </p>
            <br><p class="lead">
              <a href="{% url 'zenith:aboutus' %}" class="btn btn-lg btn-default">Learn More &rarr;</a>
            </p><br><br><br><br><br>
          </div>
        </div>

      </div>

    </div>
<footer class="footer">
      <div class="container">
        <p class="text-muted" style="text-align: center;"><a href="http://github.com/PeterOlayemi">Developer: PeterCodes</a></p>
      </div>
    </footer>
</div>
  </body>
</html>

zenith/templates/zenith/payment.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Payments</title>
        <style>
            .blog-post-title {
                margin-bottom: 5px;
                font-size: 40px;
            }
        </style>
    </head>
    <body>
    {% extends "zenith/base.html" %}

{% block header %}

    <div class=''>
        <div class="container">
        <br><br><br><br><br><h2 class="blog-post-title">Payments</h2>
        </div>
    </div>

{% endblock header %}

{% block content %}
<div style="font-size: 19px;">
<p>Hello Esteemed Student of Zenith,<br>So far so good, weldone... It is to our joy that you've decided to join this blessed tutorial. We are sure that this decision of yours will lead you to an outstanding results.<br>
And if you are still contemplating whether to join this tutorial or not, I assure you that joining us will be one of your best decisions in life.<br><br>Now, to complete this online registration, you are to pay a sum of  <u># 1 000 000</u> in the next 30 days after registration. This payment will verify your account and you will be contacted on how the tutorials will commence.<br>
Fill in <a href="{% url 'zenith:paymentfile' %}">this form &raquo;</a> after payment.<br><br>
The tutorial fee is to be paid to any of the following accounts:<br><br>
<div style="text-align:center">
Account Name: Zenith Tutorial Corp<br>
Account Number: 2005210217<br>
Bank: FirstBank<br>
</div>Or:<br>
<div style="text-align:center">
Account Name: Zenith Tutor <br>
Account Number: 3183567201<br>
Bank: United Bank for Africa<br>
</div>
<br><br>
<u><b>Kindly Note:</b></u><br><br>
<ul>
<li>Before payment, Make sure that your student profile is complete and accurate. You can check and edit your profile <a href="{% url 'zenith:studentprofile'%}">HERE &raquo;</a></li>
<li>Do not create another account. This might lead to ban and deletion of account.</li>
<li>After payments, Make sure to send your name and payment's debit alert in jpg / pdf / doc through <a href="{% url 'zenith:paymentfile' %}">HERE &raquo;</a>
<li>You will be contacted through email on your payment updates.</li>
<li>When payment is verified, you will be contacted on how your tutorials will start.</li>
<li>If your tutorial fee is not paid within 30 days of account registration, your account will be deleted.</li>
<li>To send a message to us concerning payments and other issues, you can click <a href="{%url 'zenith:message'%}">HERE &raquo;</a></li>
</li>
</p>
<br>
<a href="{% url 'zenith:home' %}" class="btn btn-lg btn-default">&laquo; Go To Home</a>
<br><br><br><br><br>
</div>
{%endblock%}

zenith/templates/zenith/paymentdetail.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Payment</title>
        <style>
            .blog-post-title {
                margin-bottom: 5px;
                font-size: 40px;
            }
        </style>
<script>
function sayadd()
{alert('Adding Payment Details... Payment Updates will be Sent to this Mail');}
</script>
    </head>
    <body>
    {% extends "zenith/base.html" %}

{% block header %}

    <div class=''>
        <div class="container">
        <br><br><br><br><br><h2 class="blog-post-title">Add Payment Details</h2>
        </div>
    </div>

{% endblock header %}

{% block content %}
<div style="font-size: 19px;">

<form method="post" class="form" enctype="multipart/form-data">

    {% csrf_token %}

    {{form.as_p}}
        <button class="btn btn-lg btn-default" onclick="sayadd()">Finish &raquo;</button>

</form><br><br>
<a href="{% url 'zenith:paymentfile' %}" class="btn btn-lg btn-default">&laquo; Go Back</a>   <a href="{% url 'zenith:home' %}" class="btn btn-lg btn-default">&laquo; Go To Home </a>
</div>
<br><br><br><br><br><br><br><br>

{%endblock%}

zenith/templates/zenith/studentprofile.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Student Profile</title>
        <style>
            .blog-post-title {
                margin-bottom: 5px;
                font-size: 40px;
            }
            .blog-post-meta {
            margin-bottom: 20px;
            color: #999;
            }
        </style>
    </head>
    <body>
    {% extends "zenith/base.html" %}

{% block header %}

    <div class=''>
        <div class="container">
        <br><br><br><br><br><h2 class="blog-post-title">Student Profile</h2>
        </div>
    </div>

{% endblock header %}

{% block content %}
<div style="font-size: 19px;">
{% for data in data %}
Verified Account: {{data.verified}}<br><br><br>
{%endfor %}
{% for data in hotel %}
Display Picture: <br><br><div style="text-align: center;"><img src="{{ data.display_picture.url }}" class="img-responsive" style="width: 30%; text-align: center;" /></div>
<br><a href="{% url 'zenith:editdp' _id=data.id%}" class="btn btn-lg btn-default">Change Display Picture &raquo;</a>
{%empty%}
<a href="{% url 'zenith:image_upload' %}" class="btn btn-lg btn-default">Add Picture / Details &raquo;</a>
{%endfor %}<br><hr><br>
Username: {{user.username|title}}<br><br>
{% for data in data %}
Date of Birth: {{data.date_of_birth}}<br><br>
School: {{data.school}}<br><br>
Phone Number: {{data.phone_number}}<br><br>
Hostel Address: {{data.hostel_address}}<br><br>
Level: {{data.level}}<br><br>
Department: {{data.department}}<br><br>
Lecture Theatre: {{data.lecture_theatre}}<br><br>
<br><br><br>
<a href="{% url 'zenith:editprofile' _id=data.id %}" class="btn btn-lg btn-default">Edit Profile &raquo;</a>   <a href="{% url 'zenith:home' %}" class="btn btn-lg btn-default">&laquo; Go To Home </a>
{%endfor %}
</div>
<br><br><br><br><br>
{%endblock%}
</body>